project:
  title: "canada_pm25_summaries"
  execute-dir: project

title: ""

knitr:
  opts_chunk: 
    warning: false
    include: false
    echo: false
    fig.width: 12
    fig.height: 5
    fig.align: center
    out.width: "100%"
    
format:
  html: 
    css: ["https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css", "index_files/css/report_stylesheet.css"]
    template: report_template.html
    embed-resources: false
    output-file: index.html
    lib-dir: libs
    pre-render: R/pre_render.R
    include-in-header:
      - text: |
          <script src="index_files/js/page_load.js"></script>
