project:
  title: "canada_pm25_summaries"


title: ""

knitr:
  opts_chunk: 
    warning: false
    include: false
    echo: false
    fig.width: 12
    fig.height: 5
    fig.align: center
    out.width: "100%"
    
output:
  html_document: 
    css: ["https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css", "css/report_stylesheet.css"]
    template: report_template.html
    self_contained: false
    lib_dir: lib
    include-in-header:
      - text: |
          <script src="js/page_load.js"></script>
