project:
  title: "canada_pm25_summaries"
  execute-dir: project
  pre-render: R/pre_render.R
  post-render: R/post_render.R

knitr:
  opts_chunk: 
    warning: false
    include: false
    echo: false
    fig.width: 12
    fig.height: 5
    fig.align: center
    out.width: "100%"

format:
  html: 
    page-layout: full
    theme: css/theme.scss
    css: "index_files/css/report_stylesheet.css"
    embed-resources: false
    output-file: index.html
    lib-dir: libs
    mainfont: Inter, sans-serif
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://rsms.me/">
          <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
          <script src="index_files/js/page_load.js"></script>

author: 
  - name: "Brayden Nilson"
    affiliation: "Environment and Climate Change Canada"
    email: brayden.nilson@ec.gc.ca
date-modified: now
license: "CC BY-NC-SA"
appendix-cite-as: display
