project:
  title: "canada_pm25_summaries"


title: ""

output:
  html_document: 
    css: ["https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css", "css/report_stylesheet.css"]
    template: report_template.html
    self_contained: false
    lib_dir: lib
    include-in-header:
      - text: |
          <script src="js/page_load.js"></script>
